version: 2.1

executors:
    php_executor:
        docker:
        - image: circleci/php:7.2

commands:
    restore_repo:
        steps:
        - restore_cache:
              keys:
              - source-{{ .Branch }}-{{ .Revision }}
              - source-{{ .Branch }}-
              - source

jobs:
    checkout_code:
        executor: php_executor
        steps:
        - restore_repo
        - checkout
        - save_cache:
              key: source-{{ .Branch }}-{{ .Revision }}
              paths:
              - ".git"

    composer_install:
        executor: php_executor
        steps:
        - restore_repo
        - checkout
        - restore_cache:
              keys:
              - composer-{{ checksum "composer.lock" }}
              - composer-
        - run: composer install
        - save_cache:
              key: composer-{{ checksum "composer.lock" }}
              paths:
              - "vendor"
        - persist_to_workspace:
              root: "."
              paths:
              - "vendor"

    deploy:
        executor: php_executor
        steps:
        - restore_repo
        - checkout
        - attach_workspace:
              at: "."
        - run: php vendor/bin/dep deploy production -vvv

workflows:
    version: 2
    build_and_deploy:
        jobs:
        - checkout_code
        - composer_install:
              requires:
              - checkout_code
        - deploy:
              requires:
              - composer_install
              filters:
                  branches:
                      only:
                      - master
